name: Integration Tests
 
on:
  pull_request:
    branches: [ develop ]
 
jobs:
  build:
 
    runs-on: macos-latest
 
    steps:
    - uses: actions/checkout@v2
     
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app
     
    - name: Build and Test
      run: xcodebuild test -project collect-toys.xcodeproj -scheme "collect-toys" -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.4'
